dsp-recover: general improvements and fixes
Based on coments from Juha Alanen.

Signed-off-by: Felipe Contreras <felipe.contreras@nokia.com>

diff --git a/scripts/dsp-recover b/scripts/dsp-recover
--- a/scripts/dsp-recover
+++ b/scripts/dsp-recover
@@ -1,12 +1,21 @@
 #!/bin/sh
 
-MODULE_USAGE=`cat /proc/modules|grep bridgedriver|head -1|cut -d ' ' -f3`
+kill_users()
+{
+        users=$(for x in `lsof -t /dev/DspBridge`; do basename `cat /proc/$x/cmdline | tr '\0' ':' | cut -f1 -d :`; done)
+        logger -s -t "dsp-recover" "FIXME! killing users of 'bridgedriver': $users"
+        kill -9 `lsof -t /dev/DspBridge`
+        sleep 5
+}
+
+MODULE_USAGE=`grep bridgedriver /proc/modules | cut -d ' ' -f3`
 COUNT=0
 while [ $MODULE_USAGE -ne 0 ]
 do
-	MODULE_USAGE=`cat /proc/modules|grep bridgedriver|head -1|cut -d ' ' -f3`
-	if [ $COUNT -ge 60 ]; then
+	MODULE_USAGE=`grep bridgedriver /proc/modules | cut -d ' ' -f3`
+	if [ $COUNT -ge 10 ]; then
                 logger -t "dsp-recover" "gave up waiting for 'bridgedriver' to become free"
+                kill_users
 		break
 	fi
 
@@ -14,9 +23,15 @@ do
         COUNT=$(($COUNT + 1))
 done
 
-/etc/init.d/dsp restart
-if [ $? != 0 ]; then
-        logger -t "dsp-recover" "initial restart failed"
-        /lib/dsp/cexec.out /lib/dsp/baseimage.dof
-        /etc/init.d/dsp restart
+modprobe -r -s -w bridgedriver
+if [ $? == 0 ]; then
+        modprobe -s bridgedriver
+else
+        logger -t "dsp-recover" "initial restart failed, reloading image"
+        /lib/dsp/cexec.out -T /lib/dsp/baseimage.dof
+fi
+if [ $? == 0 ]; then
+        logger -t "dsp-recover" "DSP restarted"
+else
+        logger -t "dsp-recover" "couldn't restart the DSP"
 fi
